version: '3.1'

services:

  wordpress:
    image: wordpress:php7.2
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./:/var/www/html/wp-content/plugins/aad-doc-manager

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
